version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
        
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - "./data/api/thumbnails:/app/thumbnails"
      - "./data/api/uploads:/app/uploads"
    depends_on:
      - redis